### ISSUE TITLE
Hawaii throws: Unhandled exception. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by abelbraaksma** [Zaid-Ajaj/Hawaii#38]
Hi @Zaid-Ajaj, I was trying out this awesome project to create a client for Stripe (using this: https://github.com/stripe/openapi/blob/master/openapi/spec3.yaml), which has an OpenApi spec in JSON and YAML. However, either way I try it, `hawaii` crashes with the following exception:

```f#
Unhandled exception. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Program.getSchema(String schema, FSharpOption`1 overrideSchema) in /Users/zaid/projects/Hawaii/src/Program.fs:line 290
   at Program.runConfig(String filePath) in /Users/zaid/projects/Hawaii/src/Program.fs:line 2767
   at Program.main(String[] argv) in /Users/zaid/projects/Hawaii/src/Program.fs:line 2920
```

This exception appears to incorrectly render the path/file name that causes the error, and "line 0, pos 0" suggests something odd is going on.

Tbh, I'm fully aware that this is a massive API from Stripe, so I wouldn't entirely expect it to go as smoothly as any smaller API. Though I also tried it with some smaller APIs and still got the same error, so maybe something else is the matter. To that end, this is the config I was using:

```json
{
  "schema": "testapi.json",        // tried with stripe's spec3.json and spec3.yaml as well
  "project": "StripeAutogen",
  "output": "./output",
  "target": "fsharp",
  "synchronous": true,
  "asyncReturnType": "async",
  "resolveReferences": false,
  "emptyDefinitions": "ignore"
  //[ "overrideSchema" ],<JSON schema subset>,
  //[ "filterTags" ]
}
```

EDIT: I get exactly the same error when I use `"schema": "thisfiledoesnotexist.yml"`, in other words, this appears to happen prior to opening the file, as with a non-existing file I receive the same error...

Version of Hawaii:

```text
hawaii --version
0.59.0
```

**Comment by Zaid-Ajaj** [comment]
HI @abelbraaksma thanks for filing the issue, not being able to parse the JSON suggests that the JSON is malformed which you can get if you are not referencing the RAW file contents from github when pointing the schema configuration at it

I will have a look when I can, right now only with access to my phone

**Comment by Zaid-Ajaj** [comment]
Hi @abelbraaksma, thanks again for digging into this 🙏 I understand the problem here it seems that Hawaii is not adequate enough to account for Stripe API at the moment. Requiring an `object` to be spread inside the query string parameters is always tricky, especially because infinite nesting is possible and we don't generate a specific type for the input (I think we should generate an object here like `GetAccountPeopleRelationshipInput` and use it in the function definition
```fs
    ///<summary>
    ///&amp;lt;p&amp;gt;Returns a list of people associated with the account’s legal entity. The people are returned sorted by creation date, with the most recent people appearing first.&amp;lt;/p&amp;gt;
    ///</summary>
    ///<param name="endingBefore">A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.</param>
    ///<param name="expand">Specifies which fields in the response should be expanded.</param>
    ///<param name="limit">A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.</param>
    ///<param name="relationship">Filters on the list of people returned based on the person's relationship to the account's company.</param>
    ///<param name="startingAfter">A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.</param>
    member this.GetAccountPeople
        (
            ?endingBefore: string,
            ?expand: list<string>,
            ?limit: int,
            ?relationship: GetAccountPeopleRelationshipInput, 
            ?startingAfter: string
        ) =
        async {
            let requestParts =
                [ if endingBefore.IsSome then
                      RequestPart.query ("ending_before", endingBefore.Value)
                  if expand.IsSome then
                      RequestPart.query ("expand", expand.Value)
                  if limit.IsSome then
                      RequestPart.query ("limit", limit.Value)
                  if relationship.IsSome then
                      RequestPart.query ("relationship[director]", relationship.Value.director)  // this is problematic
                      RequestPart.query ("relationship[executive]", relationship.Value.executive)// and this
                      RequestPart.query ("relationship[owner]", relationship.Value.owner)        // and this
                      RequestPart.query ("relationship[representative]", relationship.Value.representative) // and this
                  if startingAfter.IsSome then
                      RequestPart.query ("starting_after", startingAfter.Value) ]

            let! (status, content) = OpenApiHttp.getAsync httpClient "/v1/account/people" requestParts

            if status = HttpStatusCode.OK then
                return GetAccountPeople.OK(Serializer.deserialize content)
            else
                return GetAccountPeople.DefaultResponse(Serializer.deserialize content)
        }
```
In any case, a simpler solution is to change the indexers from say
```fs
 RequestPart.query ("relationship[director]", relationship.Value.director)
```
to
```fs
RequestPart.query ("relationship[director]", relationship.Value.["director"].ToObject<string>())
```
At the moment, I am very low on time to pick up this issue but always happy to accept PRs and review/merge them 😄

**Comment by Eliemer** [comment]
wait, does it or does it not support .yaml files? Im getting this error with a very simple API doc

**Comment by ghost** [comment]
I got this error:
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonTextReader.ParseValue()
Newtonsoft.Json.JsonTextReader.Read()
Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
Newtonsoft.Json.Linq.JObject.Parse(string json, JsonLoadSettings settings)
Newtonsoft.Json.Linq.JObject.Parse(string json)
AccountGoWeb.Controllers.AccountController.SignIn(LoginViewModel model, string returnUrl) in AccountController.cs
+
                Newtonsoft.Json.Linq.JObject resultSignIn = Newtonsoft.Json.Linq.JObject.Parse(responseSignIn.Content.ReadAsStringAsync().Result);
Microsoft.
